[package]
name = "rpi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "rpi"
test = false
bench = false

[dependencies]
bitflags = "2.5"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
