[package]
name = "kernel"
version = "0.1.0"
edition = "2021"

[dependencies]
defmt = "0.3.8"
embassy-executor = "0.6.1"
embassy-time = { version = "0.3.2", features = ["generic-queue"] }
rpi = { workspace = true }

[[bin]]
name = "kernel"
test = false
bench = false
