[build]
target = "../armv6a-none-eabihf.json"

[target.arm-none-eabihf]
rustflags = ["-C", "link-arg=-Tbootloader/link.x"]

[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]
