[build]
target = "arm-none-eabihf.json"

[target.arm-none-eabihf]
rustflags = ["-C", "link-arg=-Tlink.x"]

[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]
