[build]
target = "armv6a-none-eabihf.json"

[target.armv6a-none-eabihf]
rustflags = ["-C", "link-arg=-Tkernel/link.x"]

[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]
